package fr.univ_lyon1.info.m1.elizagpt.model;



/**
 * The ChainClient class.
 * It uses a chain of handlers to analyze and respond to user queries or statements.
 */
public class ChainClient {
    private Handler chain;
    private MessageProcessor messageProcessor;

    /**
     * Constructs a new ChainClient .
     *
     * @param messageProcessor The MessageProcessor.
     */
    public ChainClient(final MessageProcessor messageProcessor, final Handler chain) {
        this.messageProcessor = messageProcessor;
        this.chain = chain;
        // this.chain = new NameHandler(
        //                 new NameQuestionHandler(
        //                     new QuiEstLePlusHandler(
        //                         new JeHandler(
        //                             new QuestionHandler(
        //                                 new RandomResponseHandler(null))))));
    }

    /**
     * Processes user input through the chain of responsibility and returns the generated response.
     *
     * @param text The user input text to be processed.
     * @return The response generated by the chain of handlers.
     */
    public String processUserInput(final String text) {
        return chain.process(messageProcessor.normalize(text), messageProcessor);
    }
}

