package fr.univ_lyon1.info.m1.elizagpt.model;


/**
 * The Handler interface defines the contract for classes that are part of a chain of 
 * responsibility.
 * Each handler in the chain processes a specific type of input or query.
 */
public interface Handler {
    /**
     * Processes the input text and returns a response based on the specific 
     * behavior of the handler.
     *
     * @param text              The input text to be processed.
     * @param messageProcessor The MessageProcessor used for normalizing 
     * 		text and processing messages.
     * @return The response generated by the handler.
     */
    String process(String text, MessageProcessor messageProcessor);

    /**
     * Sets the next handler in the chain.
     *
     * @param next The next handler to be set in the chain.
     */
    void setNextHandler(Handler next);

    /**
     * Gets the next handler in the chain.
     *
     * @return The next handler in the chain.
     */
    Handler getNextHandler();
}
